example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_wishlist_xml, show_wishlist_json
from wishlist.views import show_wishlist_xml_by_id, show_wishlist_json_by_id
from wishlist.views import register, login_user, logout_user
from wishlist.views import show_wishlist_ajax, submit_data

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('xml/', show_wishlist_xml, name='show_wishlist_xml'),
    path('json/', show_wishlist_json, name='show_wishlist_json'),
    path('xml/<int:id>', show_wishlist_xml_by_id, name='show_wishlist_xml_by_id'),
    path('json/<int:id>', show_wishlist_json_by_id, name='show_wishlist_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('submit/', submit_data, name='submit'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from wishlist.models import BarangWishlist

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('wishlist:show_wishlist'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau password salah!')
    
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Feru Pratama Kartajaya',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
        'nama': 'Feru Pratama Kartajaya',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def show_wishlist_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_wishlist_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_wishlist_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_wishlist_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def submit_data(request):
    return render(request, "wishlist_ajax.html")

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <style>
        h1.title {
            text-align: center;
            color: white;
            padding-top: 20px;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: rgb(53, 83, 83);
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: rgb(71, 121, 121);
        }
    </style>
  </head>

  <body style="background-color: rgb(109, 146, 146);">
    <ul>
        <li><a style="color: white; font-weight:bold">Feru Pratama Kartajaya</a></li>
    </ul>
    
    <h1 class="title">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <div class="container my-4">
            <div class="row">
                <div class="col" style="text-align: right; color: white;">Username: </div>
                <div class="col"><input type="text" name="username" placeholder="Username" maxlength="16"></div>
            </div>
                    
            <div class="row">
                <div class="col" style="text-align: right; color: white;">Password: </div>
                <div class="col"><input type="password" name="password" placeholder="Password" maxlength="16"></div>
            </div>

            <div class="col my-3" style="text-align: center;"><input class="btn login_btn" type="submit" value="Login" style="background-color: rgb(53, 83, 83); color:white"></div>
        </div>
    </form>

    {% if messages %}
            {% for message in messages %}
                <p style="text-align: center;">{{ message }}</p>
            {% endfor %}
    {% endif %}     
        
    <p style="text-align: center; color: white;">Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a></p>

  </body>
  
</html>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <style>
        h1.title {
            text-align: center;
            color: white;
            padding-top: 20px;
        }

        .table-title {
            background-color: rgb(63, 45, 79);
            color: white;
            padding: 16px;
            text-align: center;
            font-weight: bold;
        }

        .table-item {
            background-color: rgb(116, 105, 127);;
            color: white;
            padding: 10px;
            text-align: center;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: rgb(53, 83, 83);
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: rgb(71, 121, 121);
        }
    </style>
  </head>

  <body style="background-color: rgb(109, 146, 146);">
    <ul>
        <li><a style="color: white; font-weight:bold">Feru Pratama Kartajaya</a></li>
        <li style="float:right"><a href="{% url 'wishlist:logout' %}">Logout</a></li>
    </ul>
    
    <h1 class="title">Wishlist</h1>

    <div class="container my-4">
        <div class="row table-title my-1">
            <div class="col">Nama Barang</div>
            <div class="col">Harga Barang</div>
            <div class="col">Deskripsi</div>
        </div>
        {% for barang in list_barang %}
        <div class="row table-item my-1">
            <div class="col">{{barang.nama_barang}}</div>
            <div class="col">{{barang.harga_barang}}</div>
            <div class="col">{{barang.deskripsi}}</div>
        </div>
      {% endfor %}
    </div>

    <p style="color: white; text-align: center;">Sesi terakhir login: {{ last_login }}<p>
  </body>
  
</html>

wishlist/templates/wishlist_ajax.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wishlist</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function refresh() {
            $(document).ready(function(){
                $.getJSON("{% url 'wishlist:show_wishlist_json' %}", function(data) {
                    var tableHtml = `<table> <div class="row table-title my-1"> <div class="col">Nama Barang</div> <div class="col">Harga Barang</div> <div class="col">Deskripsi</div> </div>`
                    $.each(data, function(i, item) {
                        tableHtml += '<div class="row table-item my-1"> <div class="col">' + item.fields.nama_barang + '</div> <div class="col">' + item.fields.harga_barang + '</div> <div class="col">' + item.fields.deskripsi + '</div> </div>'
                    })
                    tableHtml += "</table>"
                    $("#ajax_table").html(tableHtml)
                });
            });
        }
    </script>
    <style>
        h1.title {
            text-align: center;
            color: white;
            padding-top: 20px;
        }

        .table-title {
            background-color: rgb(63, 45, 79);
            color: white;
            padding: 16px;
            text-align: center;
            font-weight: bold;
        }

        .table-item {
            background-color: rgb(116, 105, 127);;
            color: white;
            padding: 10px;
            text-align: center;
        }

        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: rgb(53, 83, 83);
        }

        li {
            float: left;
        }

        li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        li a:hover {
            background-color: rgb(71, 121, 121);
        }
    </style>
  </head>

  <body style="background-color: rgb(109, 146, 146);" onload= "refresh()">
    <ul>
        <li><a style="color: white; font-weight:bold">Feru Pratama Kartajaya</a></li>
        <li style="float:right"><a href="{% url 'wishlist:logout' %}">Logout</a></li>
    </ul>
    
    <h1 class="title">Wishlist</h1>

    <div id="ajax_table" class="container my-4"></div>

    <div class="container my-5" style="padding: 2px 30px; width: 60%;">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group mt-4 mb-3">
                <h1 class="title" style="text-align: center;">Tambah Item</h1>
            </div>
            <div class="form-group my-3">
                <label class="my-2" style="color: white; font-weight:bold">Nama Barang</label>
                <input class="form-control" type="text" name="username" placeholder="Nama Barang">
            </div>
            <div class="form-group my-3">
                <label class="my-2" style="color: white; font-weight:bold">Harga Barang</label>
                <input class="form-control" type="text" name="username" placeholder="Harga Barang">
            </div>
            <div class="form-group my-3">
                <label class="my-2" style="color: white; font-weight:bold">Deskripsi</label>
                <input class="form-control" type="text" name="username" placeholder="Deskripsi">
            </div>
            <div class="form-group text-center mt-4 mb-3">
                <button class="btn btn-primary" type="submit" name="submit">Submit</button>
            </div>
        </form>
    </div>

    <p style="color: white; text-align: center;">Sesi terakhir login: {{ last_login }}<p>
  </body>
  
</html>